pipeline:
  install:
    image: danlynn/ember-cli:4.4.0
    commands:
      - npm ci
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      folder: ember-acmidm-login
when:
  event: tag
  tag: v*
